### PR TITLE
Simplified project layout and updated dependencies

### PR DESCRIPTION
**Pull request by darccio**
I'm setting my own URL shortener service (in [qn.pw](http://qn.pw), which belongs to [Qomun](http://en.qomun.com)) and I found shawty to be no go-get-friendly, so I fixed the project using project layout described in [Golang docs](http://golang.org/doc/code.html).

I also changed dependencies to current repositories (pq is now at https://github.com/lib/pq and go-sql-driver at https://github.com/go-sql-driver/mysql - all in lowercase).

### CODE REVIEW

**Comment by luuhq** [comment]
Can you give more details on "not go-get friendly?"
I believe Golang practice [discourages using relative import path](http://stackoverflow.com/a/10688069/1043276) -- I believe that is what causing the [test to fail](https://travis-ci.org/3fps/shawty/builds/5868742). Golang projects generally don't put things into an `src` folder, even if there are sub-modules (e.g. [gosexy/db](https://github.com/gosexy/db), [pq](https://github.com/lib/pq)).

The database driver imports do need to be updated, however.

**Comment by darccio** [comment]
Maybe it just a matter of taste, and I'm still a go noob, but having to do four "go get" to have shawty working is a bit awkward for me.

We are probably using different workflows. When I work on a Go project I start with a "export GOPATH=$(pwd)" and then I develop my command-line apps in the root (package main) and everything else in src/project/ (package project). How do you do?

Now I'm pretty sure I'm missing something because I tried to clone doozer and build it (with go build) and I found the same issue. It seems that current best practice isn't on tune with docs :)

**Comment by luuhq** [comment]
It is generally a good idea to have a somewhat permanent GOPATH. Example:

```
$ mkdir -p $HOME/gopath/src
$ echo 'export \$GOPATH=$HOME/gopath` >> ~/.bashrc
```

(use `.bash_profile` for OS X)

When you call `go get github.com/3fps/shawty`, everything should go into GOPATH's `src` folder, including the sub-modules. You should not have any problem building from there.

**Comment by darccio** [comment]
Ok, got it! Thanks for the lesson :)

I delete the forked repo, re-fork it and update the dependencies. You can discard this pull request.

**Pull request closed without merging**
